// will soon move bonzitv's video lists inside this javascript file to declutter meat.js

// youtube url variables
let youtube_url = "https://www.youtube.com/watch?v=";
let youtube_tiny_url = "https://youtu.be/watch?v=";
let youtube_shorts_url = "";
let youtube_embed_url = "";
let youtube_music_url = "";


/*
  "https://www.youtube.com/watch?v=97dyt7MXWpo",
  "https://www.youtube.com/watch?v=t0JyCdk5ymo",
  "https://www.youtube.com/watch?v=bzXzGMbdQfY",
  "https://www.youtube.com/watch?v=DuD_boVOl54",
  "https://www.youtube.com/watch?v=H50wW4eAFKo",
  "https://www.youtube.com/watch?v=APAcU3YBhYc",
  "https://www.youtube.com/watch?v=H50wW4eAFKo",
  "https://www.youtube.com/watch?v=MmB9b5njVbA",
  "https://www.youtube.com/watch?v=tYoO9XkCCHg",
  "https://www.youtube.com/watch?v=K0damuN_9bQ",
  "https://www.youtube.com/watch?v=hb59QZW2SCA",
  "https://www.youtube.com/watch?v=5ls7g9eH7ss",
  "https://www.youtube.com/watch?v=VJs_VALzi_8",
  "https://www.youtube.com/watch?v=GCA5CB5uUyA",
  "https://www.youtube.com/watch?v=Jz6FCFoL3k4",
  "https://www.youtube.com/watch?v=CDLyImqvqVY",
  "https://www.youtube.com/watch?v=Wt2rGmUmm2A",
  "https://www.youtube.com/watch?v=YnuYnzXUuGY",
  "https://www.youtube.com/watch?v=exjhztp_IQY"
*/

// the clusterfuck of video ids
let videoIdsCommercials = [
  youtube_url + "b2OUKjLzcEc",
  youtube_url + "Uyw-bne3G2A",
  youtube_url + "gcGI1f24eyM",
  youtube_url + "K0damuN_9bQ",
  youtube_url + "5ls7g9eH7ss",
  youtube_url + "hb59QZW2SCA",
  youtube_url + "VJs_VALzi_8",
  youtube_url + "GCA5CB5uUyA"
]
let videoIds4PM2430PM = [
  youtube_url + "n_sWTHQKr-s",
  youtube_url + "FdjXC4aDNrc",
  youtube_url + "oqwjsqLvaGA",
  youtube_url + "ewQeG4bfh7o",
  youtube_url + "J1xFJDSeHxI",
  youtube_url + "AJNF04k6hDU",
  youtube_url + "EXFJ1gUqSOI",
  youtube_url + "zvB3h2IKdYU",
  youtube_url + "ihDMzzMxsFY",
  youtube_url + "JdPibO28X6g",
  youtube_url + "BpJZAKy3-EI",
  youtube_url + "y281xhixx9I",
  youtube_url + "f-1tlzLYUE0",
  youtube_url + "LBapITUr878",
  youtube_url + "R7M2RiTgEO4",
  youtube_url + "hYC5FcjhowU",
  youtube_url + "PM2cT0GYs0k",
  youtube_url + "kX-TUNMguqQ",
  youtube_url + "CJjGRbm7AP0",
  youtube_url + "nUXNQk-GpXE",
  youtube_url + "pRIdTBDo5s0",
  youtube_url + "lnUnMD8avFo",
  youtube_url + "OHtNgbbZUHc",
  youtube_url + "IWeeGlqWjTo",
  youtube_url + "B-43bJpN9p0",
  youtube_url + "ZlJUN6ld7Uw",
  youtube_url + "cepnx5OtwMg",
  youtube_url + "CyYUtJWu67g",
  youtube_url + "kVPAH1SoJOs",
  youtube_url + "CSSucrEZru0",
  youtube_url + "voX77aqxMVM",
  youtube_url + "VMenL3FtjwY",
  youtube_url + "gMWMaYqMuvU",
  youtube_url + "9CivuYkHkdw",
  youtube_url + "nWjshODENSE",
  youtube_url + "wC85p4WwT7o",
  youtube_url + "-STfCX3_Dt8",
  youtube_url + "2npJbktaXas",
  youtube_url + "mW8HT3wTjtw",
  youtube_url + "aqJxAEc8I98",
  youtube_url + "7RTuOTLqNJg",
  youtube_url + "D-mxD6R0PZk",
  youtube_url + "gkpfOwxvP5Y",
  youtube_url + "MaOJiU7ICSs",
  youtube_url + "ldoCeoPnsr4",
  youtube_url + "kRtuL6PVM3M",
  youtube_url + "BxEn1br2hhA",
  youtube_url + "E7e2NbRTv34",
  youtube_url + "0Pw-W11hzaY",
  youtube_url + "fjOraqJJfdo",
  youtube_url + "-k2lYZmcyUs",
  youtube_url + "IpDx4Fw137U",
  youtube_url + "bIy7bGgPmu8",
  youtube_url + "wGFfIulM2aw",
  youtube_url + "xv3LBB6GAh4",
  youtube_url + "SLfbsnOG3lA",
  youtube_url + "YaRNqZT1QH4",
  youtube_url + "1cjfNYV-Z-U",
  youtube_url + "1cjfNYV-Z-U",
  youtube_url + "1cjfNYV-Z-U",
  youtube_url + "1cjfNYV-Z-U",
  youtube_url + "1cjfNYV-Z-U",
  youtube_url + "0zg7ZA8UGa8",
  youtube_url + "0zg7ZA8UGa8",
  youtube_url + "0zg7ZA8UGa8",
  youtube_url + "0zg7ZA8UGa8",
  youtube_url + "0zg7ZA8UGa8",
  youtube_url + "pOiiAdshU5Q",
  youtube_url + "pOiiAdshU5Q",
  youtube_url + "pOiiAdshU5Q",
  youtube_url + "pOiiAdshU5Q",
  youtube_url + "pOiiAdshU5Q",
  youtube_url + "pOiiAdshU5Q",
  youtube_url + "pOiiAdshU5Q",
  youtube_url + "pOiiAdshU5Q",
  youtube_url + "pOiiAdshU5Q",
  youtube_url + "pOiiAdshU5Q",
  youtube_url + "WwnSgVJcGm8",
  youtube_url + "XEwg5dwLjng",
  youtube_url + "eYo8jusJkfA",
  youtube_url + "iIBI3vVcce0",
  youtube_url + "7K7gaKhkiVg",
  youtube_url + "vX5baryGnnk",
  youtube_url + "kEkmTUobm9A",
  youtube_url + "ynWOhlnFJWQ",
  youtube_url + "ofPNauMOvFU",
  youtube_url + "LP4M4TBXg58",
  youtube_url + "LP4M4TBXg58",
  youtube_url + "LP4M4TBXg58",
  youtube_url + "lGT7GRoUsaw",
  youtube_url + "lGT7GRoUsaw",
  youtube_url + "lGT7GRoUsaw",
  youtube_url + "lGT7GRoUsaw",
];
let videoIds5PM = [
  youtube_url + "iK4BKnkW9rc",
  youtube_url + "qjqBUYQb21g",
  youtube_url + "XbI29tI5MXs",
  youtube_url + "0dnRWrsgKrU",
  youtube_url + "ohCm6YeovpQ",
  youtube_url + "HVK-KiANd_Q",
  youtube_url + "6-USBEqLicg",
  youtube_url + "QoHbvZfu1-c",
  youtube_url + "X2Q2X-7hVQw",
  youtube_url + "mR-lbatS6ts",
  youtube_url + "1wMsbj0VvVE",
  youtube_url + "Mzf_jtM8jgw",
  youtube_url + "qsATpni7B9s",
  youtube_url + "a0tSVDjQbz0",
  youtube_url + "4ES2y7bxENE",
  youtube_url + "j32-UnN6m5E",
  youtube_url + "86EkHcJsXhU",
  youtube_url + "P3Ca0X-TO1U",
  youtube_url + "UjnyCsweHOE",
  youtube_url + "G2ApsOSMX2s",
  youtube_url + "3Hssx5jy-f4",
  youtube_url + "sRih4d0Um9U",
  youtube_url + "lI-u0pJ-XEM",
  youtube_url + "tv9UIy0RCus",
  youtube_url + "wGKi7YITv84",
  youtube_url + "FQ0ZvlLi3Aw",
  youtube_url + "hlm9JW6hzu4",
  youtube_url + "W61OP5HPSU4",
  youtube_url + "PqS4Ckf01XI",
  youtube_url + "BjiWP6GdaZs",
  youtube_url + "VR6G2-BXk50",
  youtube_url + "7D6W6Dzsinw",
  youtube_url + "LWW9kyDhSGY",
  youtube_url + "s60XUkdNoNc",
  youtube_url + "PjfvbA3yaB4",
  youtube_url + "8M1fDbBTeuc",
  youtube_url + "OMtsPjcvOyA",
  youtube_url + "1n1_ocOUx4M",
  youtube_url + "8Yy_xnQTS9k",
  youtube_url + "aTYAwNeP7hw",
  youtube_url + "Cc4_lDIhhK4",
  youtube_url + "dTUrgFaXR2o",
  youtube_url + "IPQmfvcvOWI",
  youtube_url + "tHjjbHkFqVw",
  youtube_url + "UfDFvG0Px5A",
  youtube_url + "mtxjk_kIi6I",
  youtube_url + "M_U4NYPHuE8",
  youtube_url + "XmheFB3vSmM",
  youtube_url + "b9RSREv2NAE",
  youtube_url + "YcZ4vXgsGh4",
  youtube_url + "MnjMwoJpDag",
  youtube_url + "8zVTrQ54oKA",
  youtube_url + "HV7SQkbOKQQ",
  youtube_url + "urX6QcVFkHY",
  youtube_url + "Q7vthL5hIqo",
  youtube_url + "N0j6NXznknU",
  youtube_url + "u0qTJz2DUos",
  youtube_url + "UioiM5KopzU",
  youtube_url + "sDlGy1SxYGg",
  youtube_url + "dnua8QvCfB0",
  youtube_url + "FG0ydp-1mHE",
  youtube_url + "bCm-EAd_oEI",
  youtube_url + "aZ5lyqb4gUc",
  youtube_url + "2HUy60DWYek",
  youtube_url + "FEXeAlaL9cc",
  youtube_url + "ORouZmGacHk",
  youtube_url + "2v-8DArgo-Y",
  youtube_url + "1cjfNYV-Z-U",
  youtube_url + "1cjfNYV-Z-U",
  youtube_url + "1cjfNYV-Z-U",
  youtube_url + "1cjfNYV-Z-U",
  youtube_url + "1cjfNYV-Z-U",
  youtube_url + "0zg7ZA8UGa8",
  youtube_url + "0zg7ZA8UGa8",
  youtube_url + "0zg7ZA8UGa8",
  youtube_url + "0zg7ZA8UGa8",
  youtube_url + "0zg7ZA8UGa8",
];
let videoIds7PM = [
  youtube_url + "PT5HrjP-lPE",
  youtube_url + "1yfUfH1jF3g",
  youtube_url + "vN2BCZjZYWs",
  youtube_url + "oZF2RUJHV8c",
  youtube_url + "rNY5lwrmZ1w",
  youtube_url + "E7sn6tjcZgI",
  youtube_url + "kvsw74KWAIw",
  youtube_url + "OX3rC3ENFw0",
  youtube_url + "o3i64oR6Dv8",
  youtube_url + "Frm0LTTtgFo",
  youtube_url + "PFbYJ2-KpR8",
  youtube_url + "rVAxjlFU28o",
  youtube_url + "fIonJON2p9A",
  youtube_url + "Gc_DMKiz9LU",
  youtube_url + "bfk_pzQSfX8",
  youtube_url + "SKLlmJKfcI0",
  youtube_url + "r0W-607Atz0",
  youtube_url + "nGQ-nCwHYcs",
  youtube_url + "7hTge-5W3Cc",
  youtube_url + "fBHJFPqKIG0",
  youtube_url + "LvV7MOoSwy0",
  youtube_url + "MTyBtwmvEjE",
  youtube_url + "djMpH9D3NUQ",
  youtube_url + "3_uRhxkjdB4",
  youtube_url + "3VS4Nkzh-70",
  youtube_url + "jX28oxrdUVI",
  youtube_url + "dnBqjTmlLg8",
  youtube_url + "r_mwNcxuxwY",
  youtube_url + "xlyyu1Go4yU",
  youtube_url + "l8g0z8yZ6FU",
  youtube_url + "gMDgHPQ0YfI",
  youtube_url + "HjWbtUBKuUc",
  youtube_url + "WO2SCGfEYiE",
  youtube_url + "ur8ys2aglI4",
  youtube_url + "jmr5kAmIQGs",
  youtube_url + "3va3bdtT9LQ",
  youtube_url + "7vzfeyh-ow8",
  youtube_url + "v2t6iP4mWvA",
  youtube_url + "iwxbY-p_w0w",
  youtube_url + "pdO9uKpzaYU",
  youtube_url + "8iEXhbqami8",
  youtube_url + "T-BoDW1_9P4",
  youtube_url + "NgHygsNwTNk",
  youtube_url + "jPKuyeDb0mM",
  youtube_url + "EDsDnR2dzlw",
  youtube_url + "ljl1jBEY3_A",
  youtube_url + "jIwqlKDPq4s",
  youtube_url + "TGulB0MfxPs",
  youtube_url + "ehlrUPrvFuk",
  youtube_url + "vkUIyOm9hZk",
  youtube_url + "t2Jpe0I5pa4",
  youtube_url + "kHKJ9Mf8UxU",
  youtube_url + "zwz5yJR_aFA",
  youtube_url + "RdTJHVG_IdU",
  youtube_url + "WaXvbkjn-RA",
  youtube_url + "xe0P0rnsS1Q",
  youtube_url + "bBjk55hNjWw",
  youtube_url + "bBjk55hNjWw",
  youtube_url + "bBjk55hNjWw",
  youtube_url + "bBjk55hNjWw",
  youtube_url + "bBjk55hNjWw",
  youtube_url + "bBjk55hNjWw",
  youtube_url + "bBjk55hNjWw",
  youtube_url + "bBjk55hNjWw",
  youtube_url + "IyirV9lir8Q",
  youtube_url + "IyirV9lir8Q",
  youtube_url + "IyirV9lir8Q",
];
let videoIds25MinutesofMSAgent = [
  youtube_url + "qsATpni7B9s", // Angry Birds Toons
  youtube_url + "a0tSVDjQbz0",
  youtube_url + "4ES2y7bxENE",
  youtube_url + "j32-UnN6m5E",
  youtube_url + "86EkHcJsXhU",
  youtube_url + "P3Ca0X-TO1U",
  youtube_url + "UjnyCsweHOE",
  youtube_url + "G2ApsOSMX2s",
  youtube_url + "3Hssx5jy-f4",
  youtube_url + "sRih4d0Um9U",
  youtube_url + "lI-u0pJ-XEM",
  youtube_url + "tv9UIy0RCus",
  youtube_url + "iK4BKnkW9rc", // Angry Birds Stella
  youtube_url + "qjqBUYQb21g",
  youtube_url + "XbI29tI5MXs",
  youtube_url + "0dnRWrsgKrU",
  youtube_url + "ohCm6YeovpQ",
  youtube_url + "HVK-KiANd_Q",
  youtube_url + "V4we8iFk-fY", // AVGN
  youtube_url + "6M_4Yqk65f8",
  youtube_url + "9DfdRdOM_B0",
  youtube_url + "l-6WakV0kWM",
  youtube_url + "XjUz8IT0CYg",
  youtube_url + "y306cWw98a4",
  youtube_url + "qVBerX6Dzmc",
  youtube_url + "qVBerX6Dzmc",
  youtube_url + "QVS0Uks4ZUw",
  youtube_url + "sayp5lieKuU",
  youtube_url + "ofM11nPzFo0",
  youtube_url + "kMg6_IXCjo4",
  youtube_url + "1raUvGNbZFg",
  youtube_url + "3p713bNaO4A",
  youtube_url + "MYDuy7wM8Gk",
  youtube_url + "OEVzPCY2T-g",
  youtube_url + "v7poR6G3hec",
  youtube_url + "LkNvQYiM6bw",
  youtube_url + "X7-mOhP7W7k",
  youtube_url + "TLVGmvmNitg",
  youtube_url + "qF2snKCmqJo",
  youtube_url + "kZfq-IPlLF8",
  youtube_url + "omW1E7rv7IM",
  youtube_url + "g2eH3vYbdGo",
  youtube_url + "VvR_3OTxs8A",
  youtube_url + "gvnRBywkUZ0",
  youtube_url + "RL0YWB8wMDs",
  youtube_url + "M1tU61Nyv1w",
  youtube_url + "pw8tdieB30c",
  youtube_url + "bN6fxqvGBSs", // YKWBS?!
  youtube_url + "FffTJk-gFKc",
  youtube_url + "mBBwKWSxoMI",
  youtube_url + "mMoCgVDbWO0",
  youtube_url + "TSRBgfVBnjA",
  youtube_url + "oeyDkulK6lA",
  youtube_url + "wi1GWXvzhxQ",
  youtube_url + "bV0M9_NwMHY",
  youtube_url + "hdowZnCV-tc",
  youtube_url + "VsdzaEVeFEE",
  youtube_url + "nzLh9SqmqCA",
  youtube_url + "hG2otLyvuCQ",
  youtube_url + "bu3mcIfkUG8",
  youtube_url + "6Qnnxx-uHG4",
  youtube_url + "a_nZJNxf0QE",
  youtube_url + "mJPXWQDxO8Q",
  youtube_url + "9a4L-N__lJg",
  youtube_url + "v1HQJIOByQU",
  youtube_url + "Httd7YE4sAs",
  youtube_url + "UVZhVxSbaEs",
  youtube_url + "F18-BFmtVbM",
  youtube_url + "9dEpLNj0QcE",
  youtube_url + "eHEItvqF-tg",
  youtube_url + "mTcK4kynVLY",
  youtube_url + "tBUzngDUOnk",
  youtube_url + "C4Doj1AZInI",
  youtube_url + "5Ja4FkSUsAk",
  youtube_url + "kRhBahmZNAs",
  youtube_url + "eHV_5fEu3ug",
  youtube_url + "qGL3zr3xDHU",
  youtube_url + "IuAp-4j6QKQ",
  youtube_url + "dZGVp7EZ-NM", // Microsoft Agent Plays
  youtube_url + "MlqT79QfrcM",
  youtube_url + "VItMnVQ-9bM",
  youtube_url + "9GlgqAeJ89Q",
  youtube_url + "kJKM4uQs9WQ",
  youtube_url + "crX2VvHkfjE",
  youtube_url + "PSly8XQ-TQM",
  youtube_url + "nS-3kpM9Ovg",
  youtube_url + "ye1IZq1hPFE",
  youtube_url + "D0hQp05QlaQ",
  youtube_url + "6dQioyja4e8",
  youtube_url + "QWdm6mLRJxA",
  //youtube_url + "VRTuoilurZ",
  youtube_url + "d68-HZjoSQw",
  youtube_url + "dcFCucIQsv8",
  youtube_url + "AdESAUZUJr8",
  youtube_url + "OOntnyuecks",
  youtube_url + "qK99INAXX2w",
  youtube_url + "xA9rEtE895w",
  youtube_url + "1NnJnPdRLlI",
  youtube_url + "GnXiCbmBe_M",
  youtube_url + "OUr9_Ejhx9U",
  youtube_url + "f0KB3bkmbOU",
  youtube_url + "cSyMKD0WUmY",
  youtube_url + "xhXfbKaR5Qc",
  youtube_url + "Nx1Q9m2EYOQ",
  youtube_url + "5J0v7PdMHQY",
  youtube_url + "pnhuAmh9K1E",
  youtube_url + "i_wysAmPp7M",
  youtube_url + "g1HNcG0gZrw",
  youtube_url + "wooz39ArOPo",
  youtube_url + "oIej7VudwMg",
  youtube_url + "zs8Eu6Jh_Fo",
  youtube_url + "p59UV_MGmvs",
  youtube_url + "GikrLQBDJr4",
  youtube_url + "n0WNbzdBzSM",
  youtube_url + "3GI136Z82Nc",
  youtube_url + "KB5e6OyfCws",
  youtube_url + "0_KBkFzgEdo",
  youtube_url + "7KV88KarKg0",
  youtube_url + "qKw8GaFaLoA",
  youtube_url + "MmGAxGaS_cg",
  youtube_url + "otgKlXbBkG8",
  youtube_url + "pj6tI8l4YLI",
  youtube_url + "M3Ky21v3RC8",
  youtube_url + "CWIqBU4QlGk",
  youtube_url + "w4Zs5hVi3zM",
  youtube_url + "rWU48g7scMo",
  youtube_url + "UOGwOPKdO6A",
  youtube_url + "KQtdZh3cGrc",
  youtube_url + "UOGwOPKdO6A",
  youtube_url + "KQtdZh3cGrc",
  youtube_url + "0yRcRVt470I",
  youtube_url + "bHHr76V4sDQ",
  youtube_url + "wL1GZTqsJT8",
  youtube_url + "dRfL4IRKRzo",
  youtube_url + "5TYBN4vP8U4",
  youtube_url + "LpGUS98ot3c",
  youtube_url + "ggvzhhx11NI",
  youtube_url + "_VRBA64vDD4",
  youtube_url + "XyNJZ8PEWRM",
  youtube_url + "CwUeKJt0j9o",
  youtube_url + "ECEx2zQjaDc",
  youtube_url + "luIwRawbmi0",
  youtube_url + "lM4fBo8EMiE",
  youtube_url + "EbNGrNF87AA",
  youtube_url + "vPzCh5US-c4",
  youtube_url + "trerahVOkuQ",
  youtube_url + "1Xr5SfqWMmc",
  youtube_url + "O7K3tcCZwUY",
  youtube_url + "TitzY-BwoUY",
  youtube_url + "6DJh-uSK9VQ",
  youtube_url + "yl0URvSeGQs",
  youtube_url + "T9ZadKJiHIA",
  youtube_url + "3KM61CZTnOM",
  youtube_url + "yVvd_IdkbkE",
  youtube_url + "ljdupMIfAd4",
  youtube_url + "DgYsnJnQJqU",
  youtube_url + "OZ3LPIcRuQM",
  youtube_url + "y0NAhZZ9QlU",
  youtube_url + "8afdPc3Nnag",
  youtube_url + "47lQueyRCOg",
  youtube_url + "eFsaLhsdgLY",
  youtube_url + "2bdGZxzr5rI",
  youtube_url + "H8j8UFUNRWM",
  youtube_url + "QodUVp53Hgg",
  youtube_url + "yA4rw6GMr0c",
  youtube_url + "7RT22IJs2k8",
  youtube_url + "vFWNNXJJQ3o",
  youtube_url + "6FmijN4BY4c",
  youtube_url + "ybABNY3hwNU",
  youtube_url + "W7aXWQFQlVg",
  youtube_url + "ixK995Fnu1k",
  youtube_url + "XfkoZgnR2vo",
  youtube_url + "FlD3pOu8Sm8",
  youtube_url + "VcgX_koOHaA",
  youtube_url + "4mhsINjjl5c",
  youtube_url + "2gGF7Yfg9O0",
  youtube_url + "kZK-2qekq8s",
  youtube_url + "5hT9k7iNTGQ",
  youtube_url + "hmkuvXgxRsw",
  youtube_url + "lGT7GRoUsaw",
  youtube_url + "lGT7GRoUsaw",
  youtube_url + "lGT7GRoUsaw",
  youtube_url + "lGT7GRoUsaw",
  youtube_url + "lGT7GRoUsaw",
  youtube_url + "lGT7GRoUsaw",
  youtube_url + "lGT7GRoUsaw",
  youtube_url + "lGT7GRoUsaw",
  youtube_url + "LdLbRe09qas", // Android Trash
  youtube_url + "u39KUBd2Q9I",
  youtube_url + "vdCSSkMinvg",
  youtube_url + "4PAiqcv08cU",
  youtube_url + "g-r1Ug-hduw",
  youtube_url + "yZtjYbwsTg8",
  youtube_url + "HemR9r2dhZQ",
  youtube_url + "tJEk1GAqQTg",
  youtube_url + "Y4Ajyd6Hc0E",
  youtube_url + "YQa2-DY7Y_Q", // Battle for Dream Island (Requested by SF08, not sorry Konnor88)
  youtube_url + "8LY0o_CgPR8",
  youtube_url + "JfzEO9-Zlhw",
  youtube_url + "rhkgOXksmaY",
  youtube_url + "cdmVPHdpECM",
  youtube_url + "xHI-iKm31us",
  youtube_url + "6vGgsXO57bs",
  youtube_url + "Ze1p7bYXw0g",
  youtube_url + "g0wCF04ddnw",
  youtube_url + "Eg5Ja23HfhY",
  youtube_url + "yhkDgX2b7po",
  youtube_url + "U4sp10HUI6Y",
  youtube_url + "BQBmKvRd0B0",
  youtube_url + "yZqh3l3-pTM",
  youtube_url + "pf9FHBM0SLQ",
  youtube_url + "nAKk0gm73K0",
  youtube_url + "Xmh7M7TXDRE",
  youtube_url + "x4K1xKHwp0E",
  youtube_url + "4pR6Y3_ahS8",
  youtube_url + "J9udiROQchg",
  youtube_url + "6OfKK5Rt3fY",
  youtube_url + "GfFkiGgY6Pk",
  youtube_url + "KLwgTM7HBhw",
  youtube_url + "PigChYq_FrM",
  youtube_url + "ye_HKD_C5o0", // BUT WAIT, THERES MORE
  youtube_url + "26FJTtLOu2s", // BFDIA
  youtube_url + "cv1Qz0GCaxw",
  youtube_url + "hsprecnxSsE",
  youtube_url + "dXUE7OFij_I",
  youtube_url + "E174ogB49xs",
  youtube_url + "4q77g4xo9ic",
  youtube_url + "YrsRLT3u0Cg",
  youtube_url + "kaFpfSHllOw",
  youtube_url + "RZB7nTzSl3g",
  youtube_url + "rFUwZ0Vtims",
  youtube_url + "mmlPwe71JkA", // IDFB next
  youtube_url + "2Jw0dhwmi3o",
  youtube_url + "GoYe_yH0dVQ", // and that's all of them, i will NOT add BFB for christ's sake
  youtube_url + "UVUatYPScjw", // rocko's modern life
  youtube_url + "JoyB9zHYxi8",
  youtube_url + "zV7s4Dzq8wE",
  youtube_url + "rc4HyJ0XMgY",
  youtube_url + "exDjH1QJOEs", // PGG and PGG Rebooted (rated Mature Audiences)
  youtube_url + "m9JtPsnaakM",
  youtube_url + "qt7C-Pcfw-U",
  youtube_url + "tAjNijZHeC0",
  youtube_url + "aiIDeirsJoY",
  youtube_url + "OuFcuT4jSbE",
  youtube_url + "_ZzvFCLHFAg",
  youtube_url + "WiRdCDhaNTw",
  youtube_url + "28DdmrivqcQ",
  youtube_url + "i7GTdZH6km8",
  youtube_url + "49ODdYy9yAI",
  youtube_url + "92jKwR-M93I",
  youtube_url + "eniRs2KpC70",
  youtube_url + "Bm89dja7kNA",
  youtube_url + "bMhXrVh6GZA",
  youtube_url + "tXx2omKPXpA",
  youtube_url + "TpPdjZo0tGg",
  youtube_url + "ee_qZWa9DOw",
  youtube_url + "Ln5T_j1o32k",
  youtube_url + "h85K_p0jJ4o",
  youtube_url + "Lgh0kIUln-o",
  youtube_url + "6TdLkIOTkdA",
  youtube_url + "jwChUXVMmaQ",
  youtube_url + "ElLfUsh-NZw",
  youtube_url + "zgAzpu3zZNo",
  youtube_url + "hANfAmCJOAM",
  youtube_url + "NqIJoVay-aU",
  youtube_url + "W7br-y30kBs",
  youtube_url + "uLnq-vOXFUc",
  youtube_url + "WIXWIollTOE",
  youtube_url + "xNIXsaIO-NE",
  youtube_url + "4bijWcMnKyE",
  youtube_url + "DV6kqZSY5WE", // Windows Desktop Skits
  youtube_url + "eO2LgSSTXqM",
  youtube_url + "FeorAMjcV7E",
  youtube_url + "lex-Ap58niY",
  youtube_url + "exter6QAGS8",
  youtube_url + "XBRxcnne5f4",
  youtube_url + "dxtwzr-4UYo",
  youtube_url + "1q9phQT3-wc",
  youtube_url + "TD8InhMS1io",
  youtube_url + "Jn6CXHufyos",
  youtube_url + "fcPsjkhJLyw",
  youtube_url + "oxir0CFO_SU",
  youtube_url + "UitVP8YClNc",
  youtube_url + "-y9TxoTt5eQ", // SF08 Remakes
  youtube_url + "z1ApOo20pU4",
  youtube_url + "TafPUncacTE",
  youtube_url + "wNfMpAR-Oog",
  youtube_url + "iKCNlur5wRY",
  youtube_url + "yCRHUCSI20M",
  youtube_url + "sCKONPsB_Qc",
  youtube_url + "67XnrO-Cygc", // Controversial Fights
  youtube_url + "67XnrO-Cygc",
  youtube_url + "67XnrO-Cygc",
  youtube_url + "67XnrO-Cygc",
  youtube_url + "67XnrO-Cygc",
  youtube_url + "67XnrO-Cygc",
  youtube_url + "67XnrO-Cygc",
  youtube_url + "67XnrO-Cygc",
  youtube_url + "UGRVQ7KtEK4", // MS Brother
  youtube_url + "XLkwqFonfOg",
  youtube_url + "6JNqciPFPaw",
  youtube_url + "ME28jhesxoc",
  youtube_url + "KD71GxsfHlo",
  youtube_url + "gKjbU1z1OlU",
  youtube_url + "rjcJVX2fNFA", // MS Survivor
  youtube_url + "5hzRfTXSiKA",
  youtube_url + "xc6N_0YT2r8",
  youtube_url + "lLpp8VPUUfk"
];

// export variables
module.exports={
  youtube_url,
  youtube_tiny_url,
  youtube_shorts_url,
  youtube_embed_url,
  youtube_music_url,
  videoIdsCommercials,
  videoIds4PM2430PM,
  videoIds5PM,
  videoIds7PM,
  videoIds25MinutesofMSAgent
};